const String titleHading1= "Book an Appointment";
const String titleHading3 = "Schedule Live Consultation";
const String titleHading2 = "Read Prescriptions";
const String titleSmall = "Lorem Ipsum is simply dummy text of the printing and typesetting industry";
const String welcome = "Welcome To Hospital";
const String btnSignIn = "Sign In";
const String btnSignUp = "Sign Up";
const String signIn = "Sign In";
const String signUp = "Sign Up";